#!/bin/bash

logbox_home=/home/logbox

# Default hostname will be used to indicate setup of pi.
mac=$(sed s/://gi /sys/class/net/eth0/address)
mac=${mac:(-6)}
hostname="LogBox-$mac"

default_hostname="LogBox-new"
current_hostname=$(cat /etc/hostname)
if [ "$hostname" != "$current_hostname" ]
then
	echo "$hostname" | sudo tee /etc/hostname
	echo -e "127.0.0.1\t$hostname" | sudo tee --append /etc/hosts
	rm -f ~/www/logbox/cfg.dat
	
	sudo reboot
fi

until /home/logbox/os/report-ip.bash
do
	echo "Waiting for internet..."
	sleep 1
done

# TODO: Set up WiFi if config file exists.

# Update all components
declare -a component_list=("avr" "hat" "hat-update" "os")
for component in "${component_list[@]}"
do
	cd "$logbox_home/$component"
	git reset --hard
	git pull
done
cd $logbox_home

/usr/bin/logbox-hat-update

sudo crontab -u logbox "$logbox_home/os/cron.conf"

sudo touch /var/www/logbox/cfg.dat
sudo chown logbox:logbox /var/www/logbox/cfg.dat
sudo chmod a+w /var/www/logbox/cfg.dat

python os/data-log.py &
echo $! > /home/logbox/data-log.pid
