#!/bin/bash

logbox_home=/home/logbox

# Default hostname will be used to indicate setup of pi.
mac=$(sed s/://gi /sys/class/net/eth0/address)
mac=${mac:(-6)}
hostname="LogBox-$mac"

default_hostname="LogBox-new"
current_hostname=$(cat /etc/hostname)
if [ "$hostname" != "$current_hostname" ]
then
	echo "$hostname" | sudo tee /etc/hostname
	echo -e "127.0.0.1\t$hostname" | sudo tee --append /etc/hosts
	rm -f ~/www/logbox/cfg.dat

	sudo reboot
fi

# security patch
sudo apt-get update
sudo apt-get install -y apt apt-transport-https ca-certificates curl libcurl3 libssl1.0.2 libssl1.1 openssl

until /home/logbox/os/report-ip.bash
do
	echo "Waiting for internet..."
	sleep 1
done

# TODO: Set up WiFi if config file exists.

# Update any libraries or system code:
arduinoLibrariesDir=/usr/share/arduino/libraries
library_EnableInterrupt=${arduinoLibrariesDir}/EnableInterrupt
if [ ! -d $library_EnableInterrupt ]
then
	cd $arduinoLibrariesDir
	sudo git clone https://github.com/GreyGnome/EnableInterrupt.git EnableInterrupt
	cd -
	sudo reboot
fi

# Individual logbox settings:
if [ "$mac" == "9cb911" ] # 1908 test
then
	if [ ! -f /home/logbox/masson-fix-1 ]
	then
		cd /home/logbox/hat
		git fetch && git checkout 1908-masson
		cd /home/logbox/os
		git fetch && git checkout 1908-masson
		touch /home/logbox/masson-fix-1
		sudo reboot
	fi
fi

# Update all components:
rebootNeeded=false
declare -a component_list=("avr" "hat" "hat-update" "os")
for component in "${component_list[@]}"
do
	cd "$logbox_home/$component"
	git reset --hard
	gitMessage=`git pull | tail -n 1`
	if [ "$gitMessage" != "Already up-to-date." ]
	then
		rebootNeeded=true
	fi
done
cd $logbox_home

if [ "$rebootNeeded" = true ]
then
	sudo reboot
fi

sudo /usr/bin/logbox-hat-update

sudo crontab -u logbox "$logbox_home/os/cron.conf"

sudo touch /var/www/logbox/cfg.dat
sudo chown logbox:logbox /var/www/logbox/cfg.dat
sudo chmod a+w /var/www/logbox/cfg.dat

if [ "$mac" == "9cb911" ] # 1908 test
then
	if [ ! -f /home/logbox/masson-fix-2 ]
	then
		touch /home/logbox/masson-fix-2
		sudo reboot
	fi
fi

python os/data-log.py &
echo $! > /home/logbox/data-log.pid
